/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.androiddevchallenge

import android.content.Intent
import android.os.Bundle
import androidx.activity.compose.setContent
import androidx.appcompat.app.AppCompatActivity
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Card
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.livedata.observeAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.androiddevchallenge.DetailActivity.Companion.INTENT_KEY_PUPPY_ID
import com.example.androiddevchallenge.data.Puppy
import com.example.androiddevchallenge.ui.theme.Dimens
import com.example.androiddevchallenge.ui.theme.MyTheme
import com.example.androiddevchallenge.util.InjectorUtils
import com.example.androiddevchallenge.viewmodel.PuppyListViewModel
import dev.chrisbanes.accompanist.coil.CoilImage

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyTheme {
                Column {
                    TopBar()
                    MyApp { id ->
                        startActivity(
                            Intent(this@MainActivity, DetailActivity::class.java).apply {
                                putExtra(INTENT_KEY_PUPPY_ID, id)
                            }
                        )
                    }
                }
            }
        }
    }
}

// Start building your app here!
@Composable
fun MyApp(goDetail : ((Int) -> Unit)? = null) {
    val puppyListViewModel: PuppyListViewModel = viewModel(
        factory = InjectorUtils.providePuppyListViewModelFactory(LocalContext.current)
    )
    val puppyList = puppyListViewModel.puppies.observeAsState().value

    Surface(color = MaterialTheme.colors.background) {
        puppyList?.let{
            PuppyList(
                itemList = puppyList,
                itemClick = goDetail
            )
        }
    }
}

@Composable
fun TopBar() {
    Surface(elevation = 2.dp, color = MaterialTheme.colors.surface) {
        Row(modifier = Modifier.height(55.dp).fillMaxWidth(),
            horizontalArrangement = Arrangement.Center,
            verticalAlignment = Alignment.CenterVertically) {
            Image(
                painter = painterResource(R.drawable.ic_dog_logo),
                contentDescription = null,
                modifier = Modifier.size(34.dp)
            )
            Text(text="Adopt puppy", style = MaterialTheme.typography.h1, fontSize = 20.sp)
        }
    }
}

@Composable
fun PuppyList(
    itemList: List<Puppy>,
    itemClick: ((Int) -> Unit)? = null
) {
    LazyColumn {
        items(itemList) { data ->
            PuppyListItem(item = data, itemClick)
        }
    }
}
// The UI for each list item can be generated by a reusable composable
@Composable
fun PuppyListItem(item: Puppy, itemClick: ((Int) -> Unit)? = null) {
    Column(
        Modifier
            .clickable { itemClick?.invoke(item.puppyId) }
            .padding(Dimens.PaddingNormal)
            .fillMaxWidth()
    ) {
        PuppyNameAndAge(item)
        Spacer(modifier = Modifier.padding(Dimens.PaddingSmall))
        PuppyImage(item.imageUrl)
    }
}

@Composable
private fun PuppyNameAndAge(item: Puppy) {
    Column {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(text = item.name, fontWeight = FontWeight.Bold)
            Spacer(modifier = Modifier.padding(2.dp))
            Image(painter = painterResource(if(item.sex == "male") R.drawable.ic_male else R.drawable.ic_female),
                contentDescription = item.sex,
                modifier = Modifier.size(15.dp)
            )
        }
        Text(item.age)
    }
}

@Composable
private fun PuppyImage(
    imageUrl: String,
    modifier: Modifier = Modifier,
    placeholderColor: Color = MaterialTheme.colors.onSurface.copy(0.2f)
) {
    Card {
        CoilImage(
            data = imageUrl,
            contentScale = ContentScale.Crop,
            fadeIn = true,
            contentDescription = null,
            loading = {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(placeholderColor)
                )
            },
            modifier = modifier
                .fillMaxWidth()
                .height(Dimens.cardHeight)
        )
    }
}

@Preview("Light Theme", widthDp = 360, heightDp = 640)
@Composable
fun LightPreview() {
    MyTheme {
        MyApp()
    }
}

@Preview("Dark Theme", widthDp = 360, heightDp = 640)
@Composable
fun DarkPreview() {
    MyTheme(darkTheme = true) {
        MyApp()
    }
}
